name: jaguar_example_session
description: Example showcasing simplicity of using Sessions in Jaguar.
version: 2.1.1
homepage: https://github.com/Jaguar-dart/jaguar/wiki/Sessions
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=2.0.0-dev.55.0 <2.0.0'

dependencies:
  jaguar: ^2.1.10
  stencil: ^2.1.5
