name: session_vanilla
description: Example showcasing simplicity of using Sessions in Jaguar
version: 0.0.1
homepage: https://github.com/Jaguar-dart/jaguar/wiki/Sessions
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  jaguar: ^0.6.25

dev_dependencies:
  test: ^0.12.0
